# Generated by Django 5.2.4 on 2025-07-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetialIndex",
            fields=[
                (
                    "detial",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField()),
            ],
            options={
                "db_table": "detialindex",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("usrid", models.IntegerField(primary_key=True, serialize=False)),
                ("uname", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "userdata",
            },
        ),
        migrations.CreateModel(
            name="DetialViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usrid", models.IntegerField()),
                ("count", models.IntegerField()),
                (
                    "detial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.detialindex",
                    ),
                ),
            ],
            options={
                "db_table": "detialview",
                "unique_together": {("detial", "usrid")},
            },
        ),
    ]
